### ISSUE TITLE
Suggestion : icon resolution is to small to use it for some larger need

### ISSUE THREAD

**Issue by puneetsngh** [apixu/apixu-python#1]
`http://www.apixu.com/static/weather/64x64/day/113.png`

64x64 is too small can you provide for a hq icon who quality will not degrade if size increased atleast 128x128

**Comment by apixu** [comment]
__________________________________
Type your response ABOVE THIS LINE to reply

------------------------------------------------------------------------------------------------------------
Customer: Athar (Apixu)
Subject: [apixu/apixu-python] Suggestion : icon resolution is to small to use it for some larger need (#1)
------------------------------------------------------------------------------------------------------------

Apixu Team | SEP 01, 2016 | 05:40AM UTC

Hi,

We currently do not have higher resolution image.

But if you wish to use your own icons then you can very easily map them with our weather code. More here http://www.apixu.com/doc/weather-conditions.aspx


Thanks





Regards,

Apixu Team

How nice was my reply?
http://rate.apixu.com/apixu-team


------------------------------------------------------------------------------------------------------------

apixu/apixu-python | AUG 25, 2016 | 08:05AM UTC  | Original message 

`http://www.apixu.com/static/weather/64x64/day/113.png`

64x64 is too small can you provide for a hq icon who quality will not degrade if size increased atleast 128x128

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/apixu/apixu-python/issues/1




------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #: 1421.
------------------------------------------------------------------------------------------------------------




[[3d1dc69af40a038962c044e4fb8689bb912f7b82-778748049]]

**Comment by puneetsngh** [comment]
Thanx I can do this 😄

**Comment by tukaisg** [comment]
![image](https://cloud.githubusercontent.com/assets/24650244/21309598/f00a6952-c604-11e6-9985-49a633b8cf1a.png)


I am having this installation issue .
